.github/file-filters.yml
.github/workflows/presenter.deploy.docs.yml

fix(workflow): deploy docs

---

.github/file-filters.yml
.github/workflows/deploy.docs.yml
.github/workflows/test.code.yml
.gitignore
.remarkrc.json
.vuepress/config.ts
README.md
package-lock.json
package.json
presenter/README.md

- docs deploy
- main readme
- package.json
- test code
- correct dependency links
- None

feat(workflow): docs deploy

---

.vuepress/config.ts
deployment/README.md
deployment/build.docs.sh
deployment/build.presenter.sh
deployment/deploy.sh
deployment/nginx/default.conf
deployment/start.presenter.sh
deployment/webhooks/.gitignore
deployment/webhooks/hooks.json.template
deployment/webhooks/webhook.template

deploy stage via script
- None

feat(other): deploy stage via script

---

.github/workflows/deploy.docs.yml
.vuepress/config.ts
deployment/build.docs.sh
presenter/.vuepress/config.ts

- Update `presenter` from `boilerplate-frontend`
- introduce VUEPRESS_BASE variable and configure it accordingly
- None

fix(workflow): vuepress base

---

presenter/src/components/menu/FooterMenu.vue
presenter/src/locales/de.json
presenter/src/locales/en.json

German translation of the given presenter locales so far.
- fixes #23

feat(presenter): german translation

---

backend/prisma/migrations/20231214173756_newsletter_subscription/migration.sql
backend/prisma/schema.prisma
backend/src/graphql/resolvers/NewsletterSubscriptionResolver.spec.ts
backend/src/graphql/resolvers/NewsletterSubscriptionResolver.ts
backend/src/graphql/schema.ts
backend/test/helpers.ts

feat(backend): subscribe to newsletter

---

presenter/server/index.ts
presenter/vite.config.ts

performance by prerender. Serverside-rendering caused the timing problems. Solved by prerender.
- None

fix(presenter): performance by prerender

---

deployment/nginx/default.conf

nginx buffer size increase
Without this we get a 503 Bad Gateway.
- None

fix(other): nginx buffer size increase

---

presenter/src/components/sections/DataProtectionSection.test.ts
presenter/src/components/sections/DataProtectionSection.vue
presenter/src/components/sections/ImpressSection.test.ts
presenter/src/components/sections/ImpressSection.vue
presenter/src/locales/de.json
presenter/src/locales/en.json

Impressum content
This PR contributes some content for the two legal pages.
The UST-ID is still missing, but I would like to merge this, give it to the customer and have a second go on this for all changes requested and the UST-ID.
- None

feat(presenter): impressum

---

backend/src/graphql/inputs/ContactFormInput.ts
backend/src/graphql/inputs/SubscribeToNewsletterInput.ts
backend/src/graphql/resolvers/ContactFormResolver.spec.ts
backend/src/graphql/resolvers/NewsletterSubscriptionResolver.spec.ts

feat(backend): validation rules for inputs of contact form and newsletter

---

presenter/src/components/menu/TopMenu.vue

fix invisible hamburger menu on Safari iOS
- None

fix(presenter): fix invisible hamburger menu on Safari iOS

---

presenter/src/components/inputs/ContactForm.test.ts
presenter/src/components/inputs/NewsletterForm.test.ts
presenter/vitest.config.ts

feat(presenter): test response messages

---

presenter/src/components/nav/AnchorLink.test.ts
presenter/src/components/sections/FirstSection.test.ts
presenter/src/components/sections/FirstSection.vue
presenter/src/components/sections/FourthSection.test.ts
presenter/src/components/sections/FourthSection.vue
presenter/vitest.config.ts

Based on https://github.com/dreammall-earth/dreammall.earth/pull/167
- fixes #153

feat(presenter): increase coverage presenter

---

README.md

include browserstack reference as required by that service
- None

docs(other): include browserstack reference as required by that service

---

backend/src/api/Brevo.spec.ts
backend/src/api/Brevo.ts

Brevo response call fixes.
I adjusted the response call checks according to the Brevo documentation and tested this with an actual Brevo Key. The process works now properly.
There is one case which is not properly handled and that is resubscribe. This throws an error from Brevo and hence does not update the record on Brevo side. For now I think this is neglectable.
- relates https://github.com/dreammall-earth/dreammall.earth/issues/202

fix(backend): brevo response call fixes

---

presenter/src/locales/de.json
presenter/src/locales/en.json

style(presenter): replace German "du" by "Sie"

---

deployment/deploy.sh
log/.gitignore

This PR enables logging for the deploy script and all its subscripts. The output is redirected to the console and files.
There is two log files - one containing all logs and the other just the errors.
- contributes to #143

feat(other): logging on deploy

---

deployment/start.backend.sh
deployment/start.presenter.sh

This PR implements PM2 logging:
- contributes to #143 
- depends on #236

feat(other): logging for pm2

---

.github/dependabot.yml
README.md
package.json

dependabot for npm on root
This PR introduces dependabot updates for npm on root
- None

feat(other): dependabot for npm on root

---

backend/Dockerfile
backend/docker-compose.override.yml
backend/docker-compose.yml
backend/prisma/schema.prisma

chore(backend): update boilerplate backend 27 02

---

.vuepress/config.ts
package-lock.json
package.json

Updates vuepress and does required changes to the config and includes now required packages
- makes https://github.com/dreammall-earth/dreammall.earth/pull/282 obsolete
- makes https://github.com/dreammall-earth/dreammall.earth/pull/283 obsolete

chore(docu): update vuepress

---

backend/package-lock.json
backend/package.json

chore(backend): update packages backend 03 04

---

deployment/README.md
deployment/webhooks/hooks.json.template

Adjustments to be more precise on the deployment scripts & README.md
- contributes to #146

fix(other): deployment fixes

---

.github/workflows/backend.test.build.code.yml
.github/workflows/backend.test.build.docker.yml
.github/workflows/backend.test.build.docs.yml
.github/workflows/backend.test.lint.code.yml
.github/workflows/backend.test.unit.code.yml
.github/workflows/deploy.docs.yml
.github/workflows/presenter.deploy.chromatic.yml
.github/workflows/presenter.test.build.code.yml
.github/workflows/presenter.test.build.docker.yml
.github/workflows/presenter.test.build.docs.yml
.github/workflows/presenter.test.build.storybook.yml
.github/workflows/presenter.test.lint.code.yml
.github/workflows/presenter.test.unit.code.yml

Explicitly set the same Node version in all Node-relevant workflows.
- fixes #323

ci(workflow): set node version in workflows

---

backend/package-lock.json
backend/package.json

chore(backend): update packages backend 09 04

---

.github/workflows/backend.test.build.code.yml
.github/workflows/backend.test.build.docker.yml
.github/workflows/backend.test.build.docs.yml
.github/workflows/backend.test.lint.code.yml
.github/workflows/backend.test.unit.code.yml

update boilerplate backend 12 03
- will enable to finally merge https://github.com/dreammall-earth/dreammall.earth/pull/311

chore(backend): update boilerplate backend 12 03

---

presenter/src/layouts/DefaultLayout.vue
presenter/src/pages/optin/+Page.vue
presenter/src/pages/optin/__snapshots__/Page.test.ts.snap

Add pading of 44px to the optin page paragraph and margin-left of 44px to the button.
- fixes #246

fix(presenter): add padding right and left for the paragraph and add margin left for the button

---

presenter/renderer/app.ts
presenter/renderer/plugins/apollo.ts

feat(presenter): authorization header

---

presenter/.env.dist

fix enrollment url provided by .env.dist.
This is a missing change for the last update on authentik
- None

fix(presenter): fix enrollment url provided by .env.dist

---

backend/README.md
backend/package-lock.json
backend/package.json

This PR updates the backend boilerplate to use the latest packages
- None

chore(backend): update boilerplate backend 25 03

---

presenter/src/locales/index.test.ts

feat(presenter): test multiple szenarios of extractLocale

---

presenter/renderer/+onRenderHtml.ts
presenter/scripts/tests/mock.vikePageContext.ts
presenter/src/components/language/LanguageSelector.test.ts
presenter/src/components/language/LanguageSelector.vue
presenter/vite.config.ts

feat(presenter): add method for language switch that changes the url

---

backend/package-lock.json
backend/package.json

chore(backend): update boilerplate backend 30 03

---

frontend/package-lock.json
frontend/package.json

chore(frontend): update 07 04

---

backend/package-lock.json
backend/package.json

chore(backend): update backend packages 07 04

---

scripts/release.sh

bind frontend version to release script
- None

refactor(other): bind frontend version to release script

---

frontend/src/stores/authStore.spec.ts
frontend/src/stores/authStore.ts

set cookie properties same site and secure to get the silent refresh working
- None

fix(frontend): silent refresh

---

frontend/scripts/tests/mock.authService.ts
frontend/src/components/menu/TopMenu.vue
frontend/src/pages/auth/+Page.vue
frontend/src/pages/auth/Page.test.ts
frontend/src/pages/auth/__snapshots__/Page.test.ts.snap
frontend/src/pages/silent-refresh/+Page.vue
frontend/src/services/AuthService.spec.ts
frontend/src/services/AuthService.ts
frontend/src/stores/authStore.spec.ts
frontend/src/stores/authStore.ts
frontend/vitest.config.ts

Working token refresh utilizing the libraries events - https://stackoverflow.com/a/51843276
This strongly couples the AuthService with the AuthStore so they should always be sync
- None

fix(frontend): token refresh working

---

backend/src/server/logger.ts

fix(backend): no introspection query in log

---

backend/src/graphql/resolvers/ContactFormResolver.spec.ts
backend/src/graphql/resolvers/NewsletterSubscriptionResolver.spec.ts
backend/src/graphql/resolvers/RoomResolver.spec.ts
backend/src/server/server.ts

feat(backend): no logs in unit tests

---

frontend/package-lock.json
frontend/package.json
frontend/renderer/app.ts
frontend/renderer/plugins/apollo.ts
frontend/src/pages/index/+Page.vue
frontend/src/pages/index/Page.test.ts
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/stores/authStore.ts

Allows queries on setup level without building errors.
May be we want this in the boilerplate as well?
- None

feat(frontend): apollo ssr

---

.github/dependabot.yml

refactor(other): add dependabot group for root directory

---

.github/dependabot.yml

refactor(other): fix indent in .github/depenbabot.yml

---

.github/file-filters.yml
README.md

The Github workflows do not take sufficient account of whether changes have been made to the documentation in the respective push or pull request.
This pull request optimizes the workflows so that 
- documentation changes are fully taken into account by the corresponding workflows
- documentation-independent workflows are not triggered by documentation changes
- for each workflow's file filter (except linting for now)
(e.g. `'.github/workflows/backend.test.unit.code.yml'`for filter `backend-test-unit-code`)
- for all not docs-related workflow's file filter
- for all docs-related workflow's file filter
- None

ci(workflow): refine workflow file-filtering

---

frontend/src/pages/signin/+Page.vue

Shows a blank page while waiting to be redirected at /signin.
<!-- Which Issues does this fix, which are related?
- fixes #549

fix(frontend): show blank page for signin

---

backend/jest.config.json
backend/src/config/config.ts
backend/src/graphql/resolvers/dal/handleOpenRooms.ts
backend/src/graphql/schema.ts
backend/src/index.ts

* move check for open rooms from index to schema
* new config for bbb_pull_meetings
* only pull meetings if config is set
- None

refactor(backend): check for open rooms

---

.github/workflows/test.code.yml

Motivation
----------
This is a small regression from
bcfb65806c4ab1f5036d8cc8160e1893b3928592.
How to test
-----------
1. Test code job runs

fix(workflow): do not wait for deleted job

---

.github/workflows/test.code.yml

The workflow Test Code was not triggering anymore.
- None

fix(other): change the indention of if in workflow test code.

---

backend/src/api/BBB.spec.ts
backend/src/api/BBB.ts
backend/src/api/BBB/axios.spec.ts
backend/src/api/BBB/axios.ts

To clean up the main BBB api file, all the axios logic is moved to a separate file
- None

refactor(backend): axios logic in separate file

---

frontend/src/pages/join-room/+Page.vue

Ensure that the join room link is fetched with the actual data.
- None

fix(frontend): join room passes username

---

frontend/src/components/buttons/CreateButton.test.ts

Just activates and fixes two tests. (I fixed their counterparts for another PR where I didn't want them to be included.)

fix(frontend): fix and activate tests for CreateButton

---

frontend/src/components/menu/BottomMenu.vue
frontend/src/components/menu/TopMenu.vue
frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
frontend/src/layouts/__snapshots__/DefaultLayout.test.ts.snap
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/pages/room/__snapshots__/Page.test.ts.snap

The camera button is now a button, so the cursor converts into a pointer and accessibility is improved.

fix(frontend): make camera button an actual button

---

frontend/package-lock.json
frontend/src/components/tablesDrawer/TableList.test.ts
frontend/src/locales/de.json
frontend/src/locales/en.json
frontend/vitest.config.ts

Somehow the current master has errors in the CI of the frontend.
This fixes it.
- None

fix(frontend): ci requirements

---

backend/.env.dist
backend/jest.config.json

fix(backend): name missmach in environment variable

---

frontend/src/components/buttons/CreateButton.vue
frontend/src/components/buttons/CreateButtonMobile.vue
frontend/src/components/buttons/__snapshots__/CreateButton.test.ts.snap
frontend/src/components/buttons/__snapshots__/CreateButtonMobile.test.ts.snap
frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
frontend/src/layouts/__snapshots__/DefaultLayout.test.ts.snap
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/pages/room/__snapshots__/Page.test.ts.snap

- fixed the clip-pathes of the CreateButtons for desktop and mobile (button was not clickable correctly)
- #1253

fix(frontend): clip-path of CreateButton

---

frontend/src/components/buttons/CreateButton.vue

- fixed: animation wave is now limited to a useful size (animation frame)
- fixed: button list was not centered correctly 
<!-- Which Issues does this fix, which are related?
- fixes #1377

fix(frontend): animation of the wave needs min and max 

---

frontend/src/components/buttons/CreateButtonMobile.test.ts

Another attempt to fix our frontend tests.
- fixes #1189

fix(frontend): fix flaky test

---

docker-compose.yml

Motivation
----------
Side quest of #1451.
This is dead code and can be removed.
How to test
-----------
1. Nothing, `docker compose up` works just fine

refactor(docker): remove dead code

---

backend/prisma/migrations/20240723120823_many_users_many_meetings/migration.sql
backend/prisma/schema.prisma

Migration to have many users in many meetings with a given role.  Meetings are private or public
- relates #1448

feat(backend): many users in many meetings migration

---

frontend/src/components/menu/UserInfo.vue
frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
frontend/src/components/menu/__snapshots__/UserInfo.test.ts.snap
frontend/src/layouts/__snapshots__/DefaultLayout.test.ts.snap
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/pages/table/__snapshots__/Page.test.ts.snap

Deactivate SSR(Server Side Rendering) for the user's avatar to avoid a hydration mismatch.
- partly fixes  #1459

fix(frontend): deactivate SSR for avatar

---

backend/src/api/BBB.ts

feat(backend): change default layout to smart layout

---

README.md

Motivation
----------
@mahula asked for instructions how to clean up docker. I figured I could update the entire document as many things have changed already.
How to test
-----------
1. Read [the README](./README.md)

docs(other): update root folder README

---

admin/src/components/__snapshots__/PageShell.test.ts.snap
admin/src/components/menu/__snapshots__/TopMenu.test.ts.snap

Motivation
----------
I have 0 idea how that could find a way into `master` but admin unit tests are broken right now. This should fix it.
How to test
-----------
1. CI is green again

fix(admin): unit test snapshots

---

infrastructure/helmfile/README.md
infrastructure/kube-hetzner/.remarkignore

Motivation
----------
In our pair-programming today, we found out that you have to install helm plugins as well. So let's add them to the `README.md`.
How to test
-----------
1. Nothing really, just documentation

docs(other): update helmfile docs

---

.github/workflows/deployment.yml

Motivation
----------
This should make it move convenient for us to deploy feature branches.
How to test
-----------
1. This branch should already trigger the workflow, there should be tags

feat(workflow): push docker image on any branch

---

.github/workflows/admin.yml
.github/workflows/backend.yml
.github/workflows/frontend.yml
.github/workflows/presenter.yml

Motivation
----------
These workflows "tested" if docker images can be built. Since #1679 this is not necessary anymore.
How to test
-----------
1. Nothing really

refactor(workflow): obsolete workflows

---

frontend/src/components/menu/UserInfo.test.ts
frontend/src/components/menu/UserInfo.vue

Before:
After:
See as well the unit tests. The wrapper had to be remounted as the avatar was not reactive.
- None

fix(frontend): avatar reactive

---

frontend/src/layouts/DefaultLayout.vue
frontend/src/layouts/__snapshots__/DefaultLayout.test.ts.snap
frontend/src/pages/cockpit/__snapshots__/Page.test.ts.snap
frontend/src/pages/table/+Page.vue
frontend/src/pages/table/__snapshots__/Page.test.ts.snap

Use slots for routing inside dream mall button actions. The snapshot for the table page is now correct.
- fixes #1907

refactor(frontend): use slots for routing inside dream mall button drawer

---

.github/workflows/automerge.yml

Automerge Dependency Updates.
Does not merge PRs from other authors
- fixes https://github.com/dreammall-earth/dreammall.earth/issues/1595

feat(deps): automerge workflow action

---

.github/workflows/automerge.yml

use personal access token to allow dependabot merge command
- relates to #1595

fix(deps): use personal access token to allow dependabot merge command

---

frontend/renderer/plugins/vuetify.ts
frontend/src/assets/scss/dark.module.scss
frontend/src/assets/scss/light.module.scss
frontend/src/components/malltalk/settings/TableSettingsRoot.vue
frontend/src/locales/de.json
frontend/src/locales/en.json
frontend/src/pages/table/__snapshots__/Page.test.ts.snap
frontend/src/stores/tablesStore.ts

- DM Button: Style Edit Table #1919

fix(frontend): dream mall button: Style Edit Table

---

frontend/src/components/menu/LogoImage.vue

fix(frontend): make textEnabled optional. Removes tons of warnings from the console

---

frontend/src/components/malltalk/setup/TableSetup.vue

fix(frontend): fix locale key

---

frontend/src/locales/de.json
frontend/src/locales/en.json

Motivation
----------
Apparently, this was an oversight.
How to test
-----------
1. Visit http://localhost:3000/payment
2. Explanations are updated

fix(frontend): typos and translations

---

infrastructure/helmfile/environments/demo.yaml.gotmpl
infrastructure/helmfile/helmfile.yaml.gotmpl
infrastructure/helmfile/secrets/dreammall.yaml

Motivation
----------
We want to have a dedicated instance for demo purposes where we use our real user accounts.
This PR will create a new helmfile environment and updates the bootstrap password for the super admin in
`infrastructure/helmfile/secrets/dreammall.yaml`
How to test
-----------
1. Follow the README in `infrastructure/helmfile` and use `--environment demo`

feat(other): separate demo instance

---

infrastructure/helmfile/secrets/dreammall.yaml

Motivation
----------
This was probably an oversight from #1858.
How to test
-----------
1. `helmfile destroy`
2. `helmfile apply`

fix(other): reset authentik bootstrap password

---

backend/src/graphql/resolvers/starmap/starmap.spec.ts
backend/src/graphql/resolvers/starmap/starmap.ts

The limit is set by the code. If we want more stars, we have to add a fibonacci number.
- None

fix(backend): distribute up to 6976 stars

---

frontend/src/components/tablesDrawer/TableList.vue

fix(frontend): long table names for sidebar

---

infrastructure/helmfile/dreammall/values.yaml

Motivation
----------
This is the smaller part of #2140.
It can be merged already.
After merge, we should change `frontend/.env` on the vServer and redeploy.
How to test
-----------
1. Visit the deployment when it's ready: https://fix-account-data.git.dreammall.earth/

fix(frontend): account data

---

frontend/src/layouts/DefaultLayout.vue

Behaviour is now (again) like intended.

fix(frontend): fix interplay between DreamMall button / panel and tables sidebar

---

frontend/src/layouts/DefaultLayout.vue

- fixed panel overlays buttons
- drawer switch does not work any more
- panel overlays buttons

fix(frontend): dm button - Panel - Fix

---

frontend/renderer/app.ts
frontend/src/locales/de.json
frontend/src/locales/en.json

fix(frontend): if you disallow cookies the page just shows errors

---

backend/src/config/config.ts

Motivation
----------
I got this PR review: https://github.com/dreammall-earth/dreammall.earth/pull/2330/files#r1772170711
This is a quick refactor which will DRY up this file and improve readability.
If we touch this file again, we might want to use some JS validators like [ajv](https://github.com/ajv-validator/ajv).
I know that there is also ways to generate runtime validation from typescript type definitions.
How to test
-----------
1. No behaviour has changed

refactor(backend): dry config.ts

---

frontend/renderer/app.ts
frontend/renderer/plugins/apollo.ts

Motivation
----------
Follow up of #2412. It was really difficult to understand this part of the code and this PR will reduce complexity.
How to test
-----------
1. Nothing to test but please read the code and decide if it is easier to understand

feat(frontend): refactor apollo client

---

frontend/src/components/cockpit/my-tables/create-table/CreateTable.vue
frontend/src/locales/de.json
frontend/src/locales/en.json

i have changed the information. also in english. 
but the frontend/src/components/cockpit/my-tables/create-table/CreateTable.vue only has german names ? there are no locales for that
- fixes #2529

refactor(frontend): change wording

---

docker-compose.yml

fix(backend): database healthy-check retries increased

---

frontend/src/pages/join-table/useGetTableName.ts

fix(frontend): no prefetch for get table name query
