dreammall-earth/dreammall.earth

presenter/src/assets/sass/style.scss
presenter/src/components/sections/FirstSection.vue
presenter/vite.config.ts

fix(presenter): fix vike warning @

---

deployment/start.backend.sh

do not use npm to start backend since that detaches the process and does not allow pm2 to kill it again - it lingers after `pm2 stop backend` and blocks port 4000
- None

fix(other): backend startscript

---

presenter/.env.dist
presenter/renderer/utils.ts
presenter/src/components/language/LanguageSelector.test.ts
presenter/src/env.test.ts
presenter/src/env.ts
presenter/src/locales/de.json
presenter/src/locales/en.json
presenter/src/pages/_error/+title.ts
presenter/src/pages/_error/Page.test.ts
presenter/src/pages/auth/+title.ts
presenter/src/pages/auth/Page.test.ts
presenter/src/pages/datenschutz/+title.ts
presenter/src/pages/datenschutz/Page.test.ts
presenter/src/pages/impressum/+title.ts
presenter/src/pages/impressum/Page.test.ts
presenter/src/pages/index/+title.ts
presenter/src/pages/index/Page.test.ts
presenter/src/pages/optin/+title.ts
presenter/src/pages/optin/Page.test.ts
presenter/src/pages/silent-refresh/+title.ts
presenter/src/pages/silent-refresh/Page.test.ts

feat(presenter): translate page title with i18n

---

presenter/scripts/tests/plugin.pinia.ts
presenter/src/components/menu/HeaderMenu.test.ts
presenter/vitest.config.ts

feat(presenter): test header menu

---

frontend/.env.dist
frontend/src/env.ts
frontend/src/locales/de.json
frontend/src/locales/en.json
frontend/src/pages/index/+Page.vue
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/stores/authStore.ts
frontend/vitest.config.ts

This PR allows to check if the user is an admin in the frontend. If so, a button to the admin interface is rendered.
Both the `ADMIN_GROUP` and the `ADMIN_REDIRECT_URI` are configurable via `.env` file
- None

feat(frontend): clientside admin check

---

.github/dependabot.yml

To simplify maintenance and package updates for all four subdirectories (backend, admin, frontend, presenter), the automated package update PRs are bundled.
Therefor the [dependabot groups mechanism](https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/) is utilized.
Examples of the package bump bundling can be seen in the boilerplate repos
- [IT4Change/boilerplate-backend](https://github.com/IT4Change/boilerplate-backend/pulls)
- [IT4Change/boilerplate-frontend](https://github.com/IT4Change/boilerplate-frontend/pulls)

refactor(other): refine package update management by dependabot groups

---

.github/workflows/deploy.docs.yml

The Github Action [Vuepress deploy](https://github.com/marketplace/actions/vuepress-deploy) uses Node v16.
Our Vuepress Deployment requires Node v20 or higher.
The Action is replaced by [IT4C/Vuepress Build & Deploy](https://github.com/marketplace/actions/vuepress-build-deploy).
- None

ci(workflow): replace vuepress deploy action

---

.github/file-filters.yml
admin/package-lock.json
admin/package.json
frontend/package-lock.json
frontend/package.json
presenter/package-lock.json
presenter/package.json

The docs files exclusion in the file filter in #942 where to restrictive and caused package bump PRs to go through our checks,because of skipping essential testings.

fix(other): revert docs file exclusion from file filter and latest vuetify package update

---

deployment/local-testing/.gitignore
deployment/local-testing/README.md
deployment/local-testing/Vagrantfile
deployment/local-testing/bootstrap.sh

Context
-------
There was a similar PR #1263 attempting to do the same with docker. I was running into isolation issues with docker (setting hostname not allowed in the container and some system folders are read-only) and learned that for this use case, an actual hypervisor would be better and vagrant is a conventional tool to set up these virtual machines.
Motivation
----------
On the weekend we had a downtime on production because `nginx` configurations got out of sync with the code in newer releases.
To prevent this and further downtimes I suggest to check in our deployment configuration and make it *reproducible*.
This PR is an attempt to create a virtual machine that behaves as similar as possible to production and can be used as a sandbox for changes to our deployment configuration. …

build(other): test deployment locally

---

frontend/.storybook/ApolloWrapper.vue
frontend/scripts/tests/mock.apolloClient.ts
frontend/src/components/menu/BottomMenu.vue
frontend/src/components/menu/TopMenu.vue
frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
frontend/src/components/vuetify/Atoms/ListElement.stories.ts
frontend/src/components/vuetify/Atoms/ListElement.test.ts
frontend/src/components/vuetify/Atoms/ListElement.vue
frontend/src/components/vuetify/Atoms/__snapshots__/ListElement.test.ts.snap
frontend/src/components/vuetify/Molecules/SearchField.stories.ts
frontend/src/components/vuetify/Molecules/SearchField.test.ts
frontend/src/components/vuetify/Molecules/SearchField.vue
frontend/src/components/vuetify/Molecules/__snapshots__/SearchField.test.ts.snap
frontend/src/components/vuetify/Organisms/ListWithNavigationDrawer.stories.ts
frontend/src/components/vuetify/Organisms/ListWithNavigationDrawer.test.ts
frontend/src/components/vuetify/Organisms/ListWithNavigationDrawer.vue
frontend/src/components/vuetify/Organisms/__snapshots__/ListWithNavigationDrawer.test.ts.snap
frontend/src/components/vuetify/__snapshots__/ListElement.test.ts.snap
frontend/src/graphql/queries/openRoomsQuery.ts
frontend/src/layouts/__snapshots__/DefaultLayout.test.ts.snap
frontend/src/locales/de.json
frontend/src/locales/en.json
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/pages/room/__snapshots__/Page.test.ts.snap
frontend/src/stores/activeRoomStore.ts
frontend/src/stores/roomsStore.spec.ts
frontend/src/stores/roomsStore.ts
frontend/vitest.config.ts

feat(frontend): show open rooms sidebar

---

frontend/src/components/menu/BottomMenu.vue
frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
frontend/src/layouts/DefaultLayout.vue
frontend/src/layouts/__snapshots__/DefaultLayout.test.ts.snap
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/pages/room/__snapshots__/Page.test.ts.snap

Fixes this error message:
Also removes unneeded `d-lg-none` after `d-md-none` as the former implies the latter.

fix(frontend): cleanup bottom menu classes

---

.github/workflows/admin.yml
.github/workflows/backend.yml
.github/workflows/e2e.run.tests.yml
.github/workflows/e2e.yml
.github/workflows/frontend.yml
.github/workflows/presenter.yml
.github/workflows/root.yml

Motivation
----------
We see a lot of jobs being triggered because of the `push` target (any branch). This is a waste of resources, it's better to trigger on a pull request only.
`pull_request` vs `pull_request_target`
---------------------------------------
I was reading [Github documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target), quote:
> This event runs in the context of the base of the pull request, rather
> than in the context of the merge commit, as the pull_request event
does.
Then I was reading [Keeping your GitHub Actions and workflows secure](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).
The bottom line here is that the combination of `pull_request_target` and explicit code …

refactor(workflow): remove push target

---

docker-compose.override.yml

Motivation
----------
When you `docker compose build` on `origin/master` you get the following:
```
failed to solve: target stage "documentation" could not be found
```
This is an oversight from #1325.
How to test
-----------
1. `docker compose build`
2. Succeeds

fix(docker): remove backend-documentation

---

docker-compose.override.yml
docker-compose.yml

Motivation
----------
According to [docker compose docs](https://docs.docker.com/compose/compose-file/06-networks/):
> By default Compose sets up a single network for your app. Each container
> for a service joins the default network and is both reachable by other
> containers on that network, and discoverable by the service's name.
All our services are in the same network anyways, so let's remove this.
How to test
-----------
1. Nothing changes

refactor(docker): use default network

---

docker-compose.override.yml

Motivation
----------
These volumes are not in use, let's remove them. As the comment says,
the original intention was to have a different node version in the
container and the host.
This is something that we *don't* want. We want to use the same node
version *always*, see #1319.
How to test
-----------
1. Nothing to test, disabled code.

refactor(docker): remove unused volumes

---

authentik/README.md
authentik/docker-compose.test.yml
authentik/docker-compose.yml
docker-compose.override.yml
docker-compose.yml

Motivation
----------
Today I learned: Docker compose v2 has
[include](https://docs.docker.com/compose/multiple-compose-files/include/).
How to test
-----------
1. `docker compose up` from the root folder
2. All services, including authentik, start

refactor(docker): restart authentik via include

---

.github/workflows/backend.yml

The "Backend | docker-compose database" flow did not work anymore with the following error:
Run docker-compose -f docker-compose.yml up --detach --no-deps database The Compose file './docker-compose.yml' is invalid because: 'include' does not match any of the regexes: '^x-'
You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1. For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/ Error: Process completed with exit code 1.
- None

fix(workflow): change old ``docker-compose`` call to new ``docker compose``

---

frontend/package-lock.json

Motivation
----------
When I `npm install` and `npm run dev` in `frontend/` I see:
```
(node:4820) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
✘ [ERROR] Cannot start service: Host version "0.21.5" does not match binary version "0.20.2"
1 error
failed to load config from /home/robert/Development/dreammall/dreammall.earth/frontend/vite.config.ts
/home/robert/Development/dreammall/dreammall.earth/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:968
if (error) return callback(new Error(error), …
```

fix(frontend): revert to old `package-lock.json`

---

.github/auto_assign.yml
.github/workflows/pr.yml

Motivation
----------
I've heard today that we want to assign each PR to its respective author, so the name appears in the PR list on the right side: https://github.com/dreammall-earth/dreammall.earth/pulls
I keep forgetting this, so I'd say let's drop the requirement or automate this.
Feel free to reject this PR in case we drop the requirement.
How to test
-----------
1. Merge this into `master`
2. See if new PRs get auto-assigned

feat(workflow): auto-assign PR author

---

.github/workflows/pr.yml

Motivation
----------
The workflow to check semantic pull request titles will never start if not triggered on `pull_request_target`. It used to be like that, see here:
https://github.com/dreammall-earth/dreammall.earth/blame/7e674588b9ab03525a495637f2491c0313cae66a/.github/workflows/pr.yml#L4
In #1391 we accidently changed that one, too.
How to test
-----------
1. Merge this into master
2. PR title workflow will run again.

fix(workflow): PR title needs pull_request_target

---

backend/src/graphql/models/UserModel.ts
backend/src/graphql/resolvers/UserResolver.spec.ts
backend/src/graphql/resolvers/UserResolver.ts
backend/src/graphql/schema.ts

feat(backend): simple user query

---

deployment/nginx/default.conf

Motivation
----------
The websocket connection to the backend introduced in #1268 does not
work because of a unluckly nginx configuration on the vServer in
production/staging.
In #1402 I could reproduce the problem locally. After numerous
tries/errors with the nginx configuration I'm now pretty sure this will
enable websockets on production.
How to test
-----------
1. Ensure that the `frontend/.env` has the exact same values as the
currently checked in `frontend/.env.dist`:
```
PUBLIC_ENV__ENDPOINTS__GRAPHQL_URI=http://localhost:4000/
PUBLIC_ENV__ENDPOINTS__WEBSOCKET_URI=ws://localhost:4000/subscriptions
```
2. (optional) If you had to change `.env` values, run a `deployment/deploy.sh`
3. Checkout this feature branch, copy `deployment/nginx/default.conf`
into …

fix(other): nginx configuration for websockets

---

authentik/README.md
authentik/docker-compose.override.yml
docker-compose.override.yml

Motivation
----------
Side quest of #1373. The motivation for the previous name was the fear that the `docker-compose.yml` of our repository was used in production.
I've learned that this is not the case. So let's simplify our code a little.
How to test
-----------
1. `cd authentik`
2. `docker compose up`
3. E.g. mailpit is running

refactor(docker): use default file names

---

frontend/src/stores/authStore.spec.ts
frontend/src/stores/authStore.ts

In firefox. there is a warning that the same site attribute is missing on the auth cookie. This may lead to the authentication problems on production for firefox users.
This PR sets same site attribute to none to fix this warning.
- None

fix(frontend): same site attribute on auth cookie

---

frontend/.env.dist
frontend/renderer/plugins/apollo.ts
frontend/src/env.ts
frontend/src/pages/+guard.ts
frontend/src/pages/Guard.spec.ts

How to test guard:
* Logout
* navigate to localhost:3000
* you should end up on the authentik signin page
How to test global error handler
* in `backend/src/auth/authChecker.ts` line 38 `return false`
* Login via the presenter
* you should end up in an endless loop between authentik and the app, as the open room query always throws an unauthenticated error
- fixes #1449

refactor(frontend): unauthenticated redirect to signin page

---

frontend/src/components/menu/MessageIndicator.test.ts
frontend/src/components/menu/NewsIndicator.test.ts
frontend/src/components/menu/__snapshots__/MessageIndicator.test.ts.snap
frontend/src/components/menu/__snapshots__/NewsIndicator.test.ts.snap

Makes those little warnings go away:
Also corrects the components' names.

fix(frontend): pass required props to message and news indicator in tests

---

backend/src/auth/authChecker.spec.ts
backend/src/auth/authChecker.ts
backend/src/graphql/resolvers/ContactFormResolver.spec.ts
backend/src/graphql/resolvers/NewsletterSubscriptionResolver.spec.ts
backend/src/graphql/resolvers/RoomResolver.spec.ts
backend/src/graphql/resolvers/UserResolver.spec.ts
backend/src/server/context.ts
backend/src/server/server.ts

Motivation
----------
This is a side quest of #1451.
If there is an error with the prisma client, we send `UNAUTHENTICATED` instead of `INTERNAL_ERROR`. This will lead to an endless loop because the frontend redirects to `/signin` over and over again.
I also made a refactoring: I want to be able to mock the prisma client, so that it rejects with an error. It is a best practice to use the `dataSources` pattern from Apollo <= v2:
https://www.apollographql.com/docs/apollo-server/v2/data/data-sources/
In Apollo v4 you simply put it into `context`. I like the name `dataSources` though and nested the `prisma` client in there.
How to test
-----------
1. `docker compose down database -v`
2. `docker compose up database backend frontend authentik`
3. Login in at http://localhost:3000/
4. No endless …

fix(backend): endless redirects

---

frontend/src/assets/scss/dark.module.scss
frontend/src/components/menu/BottomMenu.vue
frontend/src/components/menu/TopMenu.vue
frontend/src/components/menu/__snapshots__/BottomMenu.test.ts.snap
frontend/src/components/menu/__snapshots__/TopMenu.test.ts.snap
frontend/src/components/tablesDrawer/TableList.test.ts
frontend/src/components/tablesDrawer/TableList.vue
frontend/src/components/tablesDrawer/TablesDrawer.vue
frontend/src/components/tablesDrawer/__snapshots__/TableList.test.ts.snap
frontend/src/components/tablesDrawer/__snapshots__/TablesDrawer.test.ts.snap
frontend/src/layouts/__snapshots__/DefaultLayout.test.ts.snap
frontend/src/locales/de.json
frontend/src/locales/en.json
frontend/src/pages/index/__snapshots__/Page.test.ts.snap
frontend/src/pages/room/__snapshots__/Page.test.ts.snap

Styles the open tables drawer according to Figma. Also adds messages in case of no open tables or no search results.
Also fixes these warnings: 
- fixes #1171

feat(frontend): improve open tables drawer design

---

authentik/docker-compose.yml

Motivation
----------
Side quest of #1373. Given that our current deployment does not execute
the checked in `docker-compose.yml` it should be safe to update this one.
The motivation for this change is that the documented
`docker-compose.yml` of authentik uses `v16`: https://goauthentik.io/docker-compose.yml
From: https://docs.goauthentik.io/docs/installation/docker-compose
How to test
-----------
1. `docker compose up`
2. Newer image will be downloaded

build(authentik): update postgres

---

backend/src/auth/authChecker.ts
backend/src/config/config.ts

Motivation
----------
This might also be a fix of our vServer deployment which relies on `.env` (bad idea in production, but another story).
I cannot reproduce the error on `master` though. Nevertheless, this should get merged for code quality. Then we can see if we get the `master` deployed.
I was checking the script that starts the backend in production [here](./deployment/scripts/start.backend.sh):
```
NODE_ENV=production TZ=UTC TS_NODE_BASEURL=./build pm2 start --name backend "node -r tsconfig-paths/register build/src/index.js" -l $LOG_FILE --log-date-format 'YYYY-MM-DD HH:mm:ss.SSS'
```
It's not even `npm run start` or sth. alike :(
How to test
-----------
1. `cd backend`
2. `npm run build`
3. `node -r tsconfig-paths/register build/src/index.js`
4. I was expecting to see the error on …

refactor(backend): read JWKS_URI after dotenv

---

infrastructure/bootstrap.sh

Motivation
----------
I was able to reproduce our websockets error in a local virtual machine.
This will setup the `.env` files in the respective folders if we are in
a Vagrant box.
How to test
-----------
1. Follow the [Infrastructure README](./infrastructure/README.md) to
setup a virtual machine locally
2. `cd authentik`
3. `docker compose up`
4. `docker compose exec -T postgresql psql authentik --username authentik < dump.sql`
5. Visit <http://localhost:9000/if/admin/#/core/providers> and configure
the OAuth/OpenID Provider's "Redirect URIs/Origin" to:
```
http://localhost:8080/.*
```
6. Step 5 will also avoid CORS issues so you can now visit
<http://localhost:8080/> and try to sign in there
7. In the browser developer tools you see the websockets connection
error

feat(other): env vars in local virtual machine

---

admin/package-lock.json
admin/package.json
frontend/package-lock.json
frontend/package.json
presenter/package-lock.json
presenter/package.json

We are getting tons of deprecation warnings in the frontend because Vuetify  needs to change code to avoid Sass deprecation warnings. Here is the issue of Vuetify:
https://github.com/vuetifyjs/vuetify/issues/20139
While we are waiting for this, let's pin Sass to a lower version that doesn't make trouble.

fix(frontend): pin sass to 1.74.1 to avoid deprecation warnings for vuetify

---

.github/workflows/docker.yml

Motivation
----------
This is a preparation for #1451.
I've used and adapted the example workflow from Github docs: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
How to test
-----------
1. Check out my fork: https://github.com/roschaefer/dreammall.earth/blob/master/.github/workflows/release.yml
2. Packages: https://github.com/roschaefer?tab=packages&repo_name=dreammall.earth (dreammall.earth-frontend will go soon as I deleted all its versions)

feat(workflow): create and push docker images

---

.github/workflows/docker.yml

... not under the repository owner.
Motivation
----------
I was confused how the ghcr image repository gets constructed and it seems I looked into the wrong folder within my fork.
How to test
-----------
1. The packages are here: https://github.com/orgs/dreammall-earth/packages
2. But I would say the belong to the repository: https://github.com/dreammall-earth/dreammall.earth

fix(workflow): publish packages under repository

---

.github/workflows/admin.deploy.chromatic.yml
.github/workflows/admin.yml
.github/workflows/backend.yml
.github/workflows/deploy.docs.yml
.github/workflows/docker.yml
.github/workflows/e2e.run.tests.yml
.github/workflows/e2e.yml
.github/workflows/frontend.deploy.chromatic.yml
.github/workflows/frontend.yml
.github/workflows/pr.yml
.github/workflows/presenter.deploy.chromatic.yml
.github/workflows/presenter.yml
.github/workflows/release.yml
.github/workflows/root.yml

Motivation
----------
[This comment](https://github.com/dreammall-earth/dreammall.earth/pull/1669#pullrequestreview-2217555113) on Github Action versions in Github workflows emphasizes the importance of taking measures to reduce the risk of being affected by supply chain attacks. One Measure is pinning the Github Actions in our workflows by commit hash rather than by tag.
How to test
----------
Just see the workflows work.

refactor(workflow): pin all github actions by commit hash

---

backend/Dockerfile

Motivation
----------
Otherwise, we cannot run the migrations from the docker image.
How to test
-----------
1. `docker run --rm -it ghcr.io/roschaefer/dreammall-backend:sha-4508a40a24a864b8699ddcddac5d2add1b2c6f4f npm run db:migrate`
2. See the following error:
```
> dreammall-backend@1.2.1 db:migrate
> TZ=UTC npx prisma migrate dev
Error: Could not find Prisma Schema that is required for this command.
You can either provide it with `--schema` argument, set it as `prisma.schema` in your package.json or put it into the default location.
Checked following paths:
schema.prisma: file not found
prisma/schema.prisma: file not found
prisma/schema: directory not found
See also https://pris.ly/d/prisma-schema-location
```

fix(docker): include prisma folder in migrations

---

.github/workflows/e2e.run.tests.yml
admin/.env.production
frontend/.env.production
presenter/.env.production

Motivation
----------
This is a workaround for #1504.
There is no (clean) way to accommplish runtime environment variables for our frontends. I bake them into the docker image for now. Not great, but gets things going.
How to test
-----------
1. `docker pull ghcr.io/dreammall-earth/dreammall.earth/presenter:master`
2. Signup/Signin buttons point to the hard-coded domain

feat(docker): bake env vars into docker image

---

authentik/web/dist/custom.css

Motivation
----------
On my machine, the text color is the same as the background color, effectively making the text invisible. What was that for?
Browser:
```
$ firefox --version
Mozilla Firefox 128.0.2
```
How to test
-----------
1. `cd authentik && docker compose up`
2. Visit http://localhost:9000
3. You can see what you type in the login form
- related #846

fix(authentik): make input field text visible

---

admin/Dockerfile
backend/Dockerfile
frontend/Dockerfile
presenter/Dockerfile

Motivation
----------
If you have to rebuild docker images quite often, you will be very happen for every time you can skip `npm install`. If we only `COPY` the `package.json` first and this file has not changed, docker will skip the following `npm install`.
Besides the changes remove some warnings and unnecessary comments repeating the code next to it.
How to test
-----------
1. `docker compose -f docker-compose.yml build ..` multiple times
2. Change files and run 1. again
3. It should skip the first call of `npm install`

refactor(docker): better caching during build

---

.github/workflows/release.yml

Motivation
----------
This will fix our current `master`. The referenced commit is current `v3.0.0`, see: https://github.com/pkgdeps/git-tag-action/releases/tag/v3.0.0
How to test
-----------
1. Merge
2. CI will become green again

fix(workflow): commit hash in release workflow

---

frontend/src/components/menu/UserInfo.test.ts
frontend/src/graphql/mutations/addSocialMediaMutation.ts
frontend/src/graphql/mutations/addUserDetailMutation.ts
frontend/src/graphql/mutations/removeSocialMediaMutation.ts
frontend/src/graphql/mutations/removeUserDetailMutation.ts
frontend/src/graphql/mutations/updateUserMutation.ts
frontend/src/stores/userStore.spec.ts
frontend/src/stores/userStore.ts

- Adds mutations for adding and removing user details and social media accounts
- Adds a mutation to update availability and name of a user
- Modifies the user query to contain these informations
- Updates the user store, which now uses those mutations and exposes them as actions
- Don't persist user store to avoid hydration mismatches (sorry,  unrelated, but one line)
Will be used by #1327.
- fixes part of #1018

feat(frontend): add mutations for about me, update user store and user query

---

.github/dependabot.yml

Motivation
----------
I was looking into configuration for dependabot to update the same package across multiple `package.json`s and found the [`directories` option](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories)
My goal is to update e.g. `vue` *across all subfolders* to the same version. You can check our PR list and see that the same dependency is updated separately for each folder, which is the culprit of our many dependanbot PRs.
Nevertheless, even if we don't see this behaviour, it's good to DRY our configuration files.
How to test
-----------
1. Merge this PR
2. See if dependabot updates the same package across several directories

refactor(workflow): dry dependabot.yml

---

authentik/docker-compose.yml
docker-compose.yml

Motivation
----------
Now that we're shipping our own docker images. It makes sense to add
image tags to build them with the right tag as well as be able to:
```
docker compose pull
```
How to test
-----------
1. `docker compose build`
2. `docker images` shows sth. like this:
```
REPOSITORY                                          TAG           IMAGE ID       CREATED              SIZE
ghcr.io/dreammall-earth/dreammall.earth/authentik   latest        2fb9b4dcf84c   About a minute ago   1.06GB
ghcr.io/dreammall-earth/dreammall.earth/admin       latest        9af3932c4d98   43 minutes ago       141MB
ghcr.io/dreammall-earth/dreammall.earth/presenter   latest        971f8a1dfe3f   43 minutes ago       141MB
ghcr.io/dreammall-earth/dreammall.earth/backend     latest        d0fd7f4644bb   43 …
```

refactor(docker): add image tags to docker-compose

---

frontend/src/pages/table/+Page.vue

We don't want:
Quickfix: We change the container height for the table page.

fix(frontend): avoid overlap of desktop bottom bar with BBB interfaces

---

backend/.env.dist
backend/src/api/BBB.ts
backend/src/api/BBB/types.ts
backend/src/config/config.ts
frontend/src/components/embedded-table/EmbeddedTable.vue
frontend/src/components/embedded-table/__snapshots__/EmbeddedTable.test.ts.snap
frontend/src/pages/table-closed/+Page.vue
frontend/src/pages/table/+Page.vue
frontend/src/pages/table/__snapshots__/Page.test.ts.snap

BBB redirects the iframe of the table page to the table-closed page, which sends a postMessage message to the iframe's parent, which in turn triggers a redirect to the start page.
- fixes #706
- Checkout this branch
- Run backend and frontend
- Open http://localhost:3000
- Open a table
- Set iframe src manually / in console to '/page-closed'

fix(frontend): table page iframe after meeting ended

---

frontend/src/graphql/mutations/updateMyTableMutation.ts

The frontend had a mutation that was named updateMyRoom this does not exists anymore. 
So we don't have errors in the frontend the PR rename the old mutation to updateMyTable.
Fix following error:
- None

fix(frontend): update my table mutation

---

backend/src/graphql/pubSub.ts
backend/src/graphql/resolvers/TableResolver.spec.ts
backend/src/graphql/resolvers/TableResolver.ts
backend/src/graphql/resolvers/dal/handleOpenTables.ts
frontend/src/stores/userStore.spec.ts

There are still instances of `room` wordings left, but we changed the term to `table`.

refactor(other): rename all remaining "room" to "table"

---

frontend/scripts/tests/mock.vikePageContext.ts
frontend/src/pages/table/Page.test.ts

pageContext can change and we can (and do) watch on it. (`src/pages/table/+Page.vue` line 26)
When testing, we get:
This PR fixes the problem by making mockPageContext reactive.

fix(frontend): reactive mock page context

---

frontend/src/components/buttons/SimpleButton.vue
frontend/src/components/cockpit/options-list/OptionButton.vue
frontend/src/components/cockpit/options-list/OptionsList.vue
frontend/src/panels/PanelHeader.vue
frontend/src/panels/dreammall/TableSetupStepC.vue
frontend/src/panels/dreammall/TableSetupStepD.vue
frontend/src/panels/dreammall/components/UserInvitationItem.vue

`defineProps` and `defineEmits` are vue compiler macros and don't need to be imported. So let's remove the imports.

fix(frontend): remove imports for defineProps and defineEmits. 

---

frontend/src/locales/de.json
frontend/src/locales/en.json
frontend/src/pages/table/+Page.vue
frontend/src/pages/table/Page.test.ts

Shows a simple table not found message instead of broken iframe when table cannot be joined or does not exist.
- fixes #1873

fix(frontend): show table not found message instead of broken iframe

---

docker-compose.override.yml
docker-compose.yml

Motivation
----------
I got quite annoyed to run the database migrations manually when doing
a `docker compose down -v` and `docker compose up`.
This will help a little.
Inspired by: https://stackoverflow.com/a/44283611
Healthcheck configuration: https://mariadb.com/kb/en/using-healthcheck-sh/
How to test
-----------
1. `docker compose down -v`
2. `docker compose up`
3. Migrations are auto-applied
For production:
1. `docker compose -f docker-compose.yml down -v`
2. `docker compose -f docker-compose.yml up`
3. Migrations are auto-applied

refactor(other): auto-migrate with docker-compose

---

.github/workflows/automerge.yml

give all permissions to the automerge job.
This is undocumented but might be the correct solution.
Ressources:
- https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/243
- https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
- relates https://github.com/dreammall-earth/dreammall.earth/issues/1595

fix(deps): give all permissions to the automerge job

---

frontend/src/components/cockpit/about-me/AboutMeView.vue
frontend/src/components/cockpit/about-me/EditSocialMedia.vue
frontend/src/components/cockpit/about-me/EditUserDetails.vue
frontend/src/components/cockpit/about-me/__snapshots__/AboutMeView.test.ts.snap
frontend/src/components/cockpit/about-me/__snapshots__/EditSocialMedia.test.ts.snap
frontend/src/components/cockpit/about-me/__snapshots__/EditUserDetails.test.ts.snap
frontend/src/components/cockpit/cockpit-card/CockpitCard.vue
frontend/src/components/cockpit/cockpit-card/__snapshots__/CockpitCard.test.ts.snap
frontend/src/components/cockpit/cockpit-layout/CockpitLayout.vue
frontend/src/components/cockpit/my-tables/MyTables.vue
frontend/src/components/cockpit/my-tables/__snapshots__/MyTables.test.ts.snap
frontend/src/pages/cockpit/+Page.vue
frontend/src/pages/cockpit/__snapshots__/Page.test.ts.snap

Motivation
----------
This is obsolete because we use CSS grid around CockpitCard components.
-----------
1. Nothing has changed
2. One property less

refactor(frontend): remove unnecessary prop narrow

---

frontend/src/components/cockpit/my-tables/create-table/TableCreated.vue

The button in the last step of the create table flow is not visible.
This PR imports the button, so it is visible.
- relates #2011

fix(frontend): add missing button at end of create table flow

---

backend/src/graphql/resolvers/TableResolver.spec.ts
backend/src/graphql/resolvers/TableResolver.ts

We can not delete MyTable and we most likely don't want to give moderation right to my table to other users. Each time we click on Join My Table we create a new Table so it is not needed in the My Tables list.
- None

feat(backend): remove MyTable from tables query

---

backend/src/graphql/resolvers/TableResolver.spec.ts
backend/src/graphql/resolvers/TableResolver.ts

Motivation
----
If a user set a meeting to private he want to be sure that no other user as the ones invited can see the meeting.
Test
----
Create a private table invite multiple users then open the table. 
On another tab delete the table from the cockpit my tables section.
Now this table is not present in the table side bar.
- None

feat(backend): check user right to get meeting information.

---

frontend/src/env.ts

Motivation
----------
Side quest of #1994.
No one takes notices of this because we have too many sources of truth.
I vote to remove all values from `.env.dist` and make the source code the single source of truth.
How to test
-----------
1. Remove `PUBLIC_ENV__AUTH__REDIRECT_URI` from your `.env`
2. You will see an authentication error

fix(frontend): wrong redirect_uri default

---

.env.dist
.gitignore
authentik/docker-compose.yml
docker-compose.yml

Motivation
----------
Side quest of #1994:
We push our docker images to Github's container registry here: https://github.com/orgs/dreammall-earth/packages?repo_name=dreammall.earth
With this change, we will be able to pull these images and test them locally. This speeds up development significantly, especially since on my machine it takes ages to build `frontend` and `presenter`.
Setting `BREVO` environment variables was necessary so that the backend server does not terminate immediately.
How to test
-----------
1. From the root directory: ``` echo "IMAGE_TAG=<image_tag>" > .env ```
2. `docker compose -f docker-compose.yml pull`
3. Images get downloaded from container registry

feat(docker): pull and test docker images locally

---

.github/dependabot.yml

This PR removes the grouping of Dependabot updates since that is incompatible with our new automerge feature (uses PR title to determine the version).
Furthermore I enable the rebaseing of the dependabot PRs, since I expect that the automerge can only merge one PR and then requires manual interaction for rebasing of the dependabot PRs.
There was a reason why we could not rebase automatically, but since its not documented and I do not know it anymore, I'd like to try again.
- None

fix(deps): dependabot remove groups & enable rebase

---

.github/workflows/frontend.yml
frontend/package-lock.json
frontend/package.json

revert typescript update to have lintfix working
Furthermore I included lintfix in our workflow runs to detect this in the future
Before:
After:
- None
While in the past this never was a problem, with the update to `typescript 5.6.2` `eslint` and `eslint --fix` behave differently causing the bug described above

fix(frontend): revert typescript update to have lintfix working

---

infrastructure/helmfile/environments/default.yaml.gotmpl
infrastructure/helmfile/scripts/branch.sh
infrastructure/helmfile/scripts/image_tag.sh

Motivation
----------
After #1994 branch deployments are getting used more often, because it became much easier.
This PR will make branch deployments even easier by providing defaults to `IMAGE_TAG` and `BRANCH`. You can still override these if you set the environments.
There is of course the risk of deploying an image tag that has not been pushed to our container registry, yet. But I guess that's something the developer would look out for.
This is how it looks if you forgot to push your branch:
As soon as you push your branch and the image tag gets pushed to the container registry, the deployment will recover:
How to test
-----------
1. `cd infrastructure/helmfile`
2. `helmfile diff`
3. Does not complain about missing required environments

feat(other): easier deployments with defaults

---

backend/src/graphql/resolvers/TableResolver.spec.ts
backend/src/graphql/resolvers/TableResolver.ts

The application can't be cleaned if we are the last moderator in a group table.
Delete the table if we are the last moderator in the table.
- fixes #2142

feat(backend): remove meeting that has no more moderators

---

infrastructure/helmfile/secrets/authentik.yaml
infrastructure/helmfile/values/authentik.yaml.gotmpl

Motivation
----------
This will allow us to test signup and other workflows on `*.git.dreammall.earth`.
We decided not to deploy mailpit in these environments and re-use the same credentials/account as in production.
close #1911
How to test
-----------
1. Test signup on https://add-authentik-smtp-configuration.git.dreammall.earth

build(authentik): add smtp configuration

---

Dockerfile
backend/Dockerfile
frontend/Dockerfile
presenter/Dockerfile

Motivation
----------
The github action [docker metatadata-action](https://github.com/docker/metadata-action/) sets a number of labels for us.
We never properly set them in our CI and now they're redundant.
If you do `docker inspect 2f6a43daaef6` you see this:
`org.opencontainers.image.created` is the `BUILD_DATE`
`org.opencontainers.image.revision` is the `BUILD_COMMIT`
`org.opencontainers.image.version` is currently the git branch and would be `BUILD_VERSION` if we would trigger the workflow with a tag. See here: https://github.com/docker/metadata-action?tab=readme-ov-file#json-output-object
How to test
-----------
1. Nothing to test here

refactor(docker): remove redundant labels

---

frontend/src/components/cockpit/my-tables/MyTables.vue
frontend/src/components/cockpit/my-tables/__snapshots__/MyTables.test.ts.snap
frontend/src/pages/cockpit/__snapshots__/Page.test.ts.snap

The message for an empty tables list is now at a more reasonable place.
- fixes #2167

fix(frontend): fix position of empty tables list message

---

backend/src/context/context.ts
backend/src/graphql/resolvers/StarmapResolver.ts
backend/src/graphql/resolvers/TableResolver.ts
backend/src/graphql/resolvers/UserResolver.ts
backend/src/prisma.ts

Motivation
----------
We already have `prisma` as `dataSource` in our `ContextValue`. This PR will import them in our resolvers.
We're not fully done yet, there are imports of `prisma` elsewhere. However, it's good for now. The code of the resolvers get copy+pasted, so it's important to refactor this part already.
How to test
-----------
1. `npm run test:unit`
2. All tests pass

refactor(backend): inject prisma via contextValue

---

backend/src/auth/authChecker.spec.ts
backend/src/context/context.ts
backend/src/graphql/resolvers/StarmapResolver.spec.ts
backend/src/graphql/resolvers/TableResolver.spec.ts
backend/src/graphql/resolvers/UserResolver.spec.ts
backend/test/mockContextValue.ts

Motivation
----------
This came out of #2287 - we will probably not merge that PR, but at least we can merge this part here.
If we pass `CONFIG` via dependency injection in `contextValue` we don't have to mock entire javascript modules in the tests. Instead, we can set dependencies per test case.
For `BBB` it would make sense to mock `axios` for example instead of our own code. Always try to mock as little as possible.
How to test
-----------
1. `npm run test:unit`

refactor(backend): pass CONFIG in contextValue

---

backend/src/graphql/resolvers/TableResolver.spec.ts
backend/src/graphql/resolvers/TableResolver.ts

… refactor the delete table method, that this error is catched before
```bash
console.log
2024-09-24 10:37:26.928     ERROR   /src/prisma.ts:37       mainLogger      Prisma Error {
message: '\n' +
'Invalid `prisma.usersInMeetings.delete()` invocation:\n' +
'\n' +
'\n' +
'An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.',
target: 'usersInMeetings.delete',
timestamp: 2024-09-24T10:37:26.927Z
}
at Object.transportFormatted (node_modules/tslog/dist/cjs/runtime/nodejs/index.js:116:13)
console.log
2024-09-24 10:37:26.944     ERROR   /src/graphql/resolvers/TableResolver.ts:421     mainLogger      User could not be detached
PrismaClientKnownRequestError  
Invalid `prisma.usersInMeetings.delete()` invocation:
An …
```

fix(backend): catch error of leaving a table you do not join

---

backend/src/graphql/resolvers/TableResolver.spec.ts
backend/src/graphql/resolvers/TableResolver.ts

To join a table as guest, the client expects to know the name of the table. Here it is.
- None

feat(backend): get table name query

---

backend/src/graphql/models/TableModel.ts
backend/src/graphql/models/UserModel.ts
backend/src/graphql/resolvers/TableResolver.ts

Motivation
----------
This is a side-quest for #2141.
In order to display a table as "always open" we need a way to construct an `OpenTable` without a BBB `meeting`.
It doesn't hurt to merge this refactoring upfront.
How to test
-----------
1. No behaviour has changed

refactor(backend): static constructor

---

docker-compose.yml

Motivation
----------
If you do a `git clean -dfx` (-> `rm presenter/.env`) and you start `docker compose up` you won't be able to signin. Because you get redirected to `http://localhost:3001/"http:/localhost:3000/signin"` which is obviously a bug.
How to test
-----------
1. `rm presenter/.env`
2. `docker compose up`
3. Visit http://localhost:3001/
4. Click on "Signin"
5. You get redirected to Authentik

fix(presenter): env defaults in docker-compose.yml

---

backend/src/graphql/resolvers/TableResolver.ts
frontend/src/graphql/subscriptions/updateOpenTablesSubscription.ts
frontend/src/stores/tablesStore.ts

Motivation
----------
This is quite a security fix. By setting the current user via arguments, it was possible to update tables as any user.
How to test
-----------
1. There is no quick way to reproduce this. Maybe just check the code changes.

fix(backend): use context.user in subscriptions

---

backend/src/api/BBB.ts

Motivation
---
On the SMART_LAYOUT we have a border from the presentation to the complete box and on small devices this makes the presentation even less visible.
Solution
---
Change the default layout to CUSTOM_LAYOUT does not change the mobile interaction.
- fixes https://github.com/dreammall-earth/dreammall.earth/issues/2260

feat(backend): change custom bbb layout to custom

---

backend/.env.dist
backend/src/config/config.ts
backend/src/logger.ts
backend/test/mockConfig.ts

Motivation
----------
This will allow us to set the global logger's log level with an
environment variable.
How to test
-----------
1. Put e.g. a `logger.trace` somewhere
2. Run the code
3. No output
4. `export LOG_LEVEL=SILLY`
5. Run the code
6. Log output happens

feat(backend): configure log level

---

backend/.env.dist
backend/src/config/config.ts
backend/src/logger.ts
backend/test/mockConfig.ts

Motivation
----------
For reasons unknown, this commit breaks the backend on our vServer deployment:
```
/root/.pm2/logs/backend-error.log last 15 lines:
0|backend  | 2024-10-10 23:52:20.281:             ^
0|backend  | 2024-10-10 23:52:20.281:
0|backend  | 2024-10-10 23:52:20.281: Error: BREVO_SEND_CONTACT functionality is disabled - some BREVO configs are missing
0|backend  | 2024-10-10 23:52:20.281:     at /var/www/localhost/htdocs/dreammall.earth/backend/build/src/api/Brevo/printConfigError.js:9:19
0|backend  | 2024-10-10 23:52:20.281:     at validateConfig (/var/www/localhost/htdocs/dreammall.earth/backend/build/src/api/Brevo/configChecks.js:20:63)
0|backend  | 2024-10-10 23:52:20.281:     at createBrevoClient (/var/www/localhost/htdocs/dreammall.earth/backend/build/src/api/Brevo/Brevo …
```

revert(backend): fix vserver deployment

---

backend/.env.dist
backend/src/config/config.ts
backend/src/logger.ts
backend/test/mockConfig.ts

Motivation
----------
Both PRs https://github.com/dreammall-earth/dreammall.earth/pull/1868 and https://github.com/dreammall-earth/dreammall.earth/pull/2446 broke our vServer deployment.
How? Well, if you load `#config/config` before `prisma` then we load this line first: https://github.com/dreammall-earth/dreammall.earth/blob/master/backend/src/config/config.ts#L10
Which means we read `'../../.env'` relative to `__dirname` which is different after `npm run build`, it's now in `build/src/config/` not `src/config`. So, our `process.env` vars are already `undefined` *but given* when `prisma` reads the `.env` file. That's how we end up with the error.
Removing the optional `path` will load from the default location that is `path.resolve(process.cwd(), '.env')`.
See: …

fix(backend): load .env vars before prisma

---

backend/.eslintrc.cjs
backend/package-lock.json
backend/package.json
backend/src/api/BBB/index.ts
backend/src/api/Brevo/Brevo.ts
backend/src/context/context.ts
frontend/.eslintrc.cjs
frontend/package-lock.json
frontend/package.json
frontend/src/components/sepa-iban/SepaIban.vue
frontend/src/components/sepa-iban/qrCode.ts
presenter/.eslintrc.cjs
presenter/package-lock.json
presenter/package.json
presenter/src/components/forms/ContactForm.vue
presenter/src/components/forms/NewsletterForm.vue
presenter/src/pages/optin/+Page.vue

Motivation
----------
This PR will prevent errors from silently failing. It's a common bug to have a `try/catch` and some error thrown which is *not* the one the developer was looking for.
Have a look at this PR for example: https://github.com/dreammall-earth/dreammall.earth/pull/2405#pullrequestreview-2333456869
close #1548
How to test
-----------
1. Write a `try/catch` where you don't rethrow the `error`
2. `npm run test:lint:eslint`
3. Will fail

refactor(other): eslint no-catch-all

---

backend/src/server/sentry/createApolloPlugin.spec.ts
backend/src/server/sentry/createApolloPlugin.ts

Motivation
----------
We see plenty `AuthenticationError`s on Sentry.
Apparently, the provided `AuthChecker` from `type-graphql` does not throw `AuthorizationError` but `AuthenticationError`. (why? 🤷‍♂️)
How to test
-----------
1. `git switch master`
2. `docker compose up database migrations backend authentik authentik-worker`
3. Visit http://localhost:4000/
4. Send:
```graphql
{
currentUser {
id
}
}
```
5. See:
```
{
"errors": [
{
"message": "Access denied! You need to be authenticated to perform this action!",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"currentUser"
],
"extensions": {
"code": "UNAUTHENTICATED",
"stacktrace": [
"GraphQLError: Access denied! You need to be authenticated to perform this action!",
"    at new AuthenticationError …
```

fix(backend): silence AuthenticationError

---

backend/src/context/context.spec.ts
backend/src/context/context.ts

Motivation
----------
I wanted to reproduce the case where we receive a generic `Error` with message `JWS verification failed` that is not an instance of any `jose.errors`.
I couldn't reproduce the case, so I deleted that condition. We will see any not-handled errors on Sentry.
Instead I found two cases that we also want to ignore:
* JOSENotSupported when the JWT has an algorithm that is not `RS256`. This is the case if someone sends a parseable JWT that does not belong to us, e.g. the default token from https://jwt.io/. That one has the headers `{ "alg": "HS256", "typ": "JWT" }`.
* JWKSNoMatchingKey this will happen when you `docker compose down -v` and `docker compose up` locally. The `kid` in the header will not match the one from Authentik anymore.
How to test
-----------
1. See …

fix(backend): ignore 2 more jose error classes

---

backend/src/api/Brevo/Brevo.spec.ts
backend/src/api/Brevo/Brevo.ts
backend/src/api/Brevo/index.ts
backend/src/context/context.spec.ts
backend/src/context/context.ts
backend/src/context/expressContext.ts
backend/src/context/subscriptionContext.ts
backend/src/server/sentry/index.ts
backend/src/server/server.ts
backend/test/mockContextValue.ts

Motivation
----------
So, this should fix #2680 and fix #2589.
I was not able to reproduce the error in a manual E2E test. @ulfgebhardt do you know how to reproduce the catch block with Brevo?
I hoped to "unsubscribe" to a newsletter and resubscribe again to get into the catch block, but that would only trigger the "happy path" (status code 2XX).
How to test
-----------
1. `cd backend`
2. `npm install`
3. `npm run test:unit`
4. Tests pass

feat(backend): log unexpected brevo api responses

---

infrastructure/helmfile/dreammall/templates/backend-deployment.yaml
infrastructure/helmfile/dreammall/templates/secret-env.yaml
infrastructure/helmfile/secrets/dreammall.yaml

Motivation
----------
We used to have brevo mocked out on our kubernetes cluster. I guess it would be best to be able to test it there as well.
This PR makes use of `envFrom.secretRef` which I found easier to maintain than enumerating all env vars.
How to test
-----------
1. Deploy to kubernetes
2. `k9s` check if env vars are set correctly

feat(backend): test brevo on kubernetes cluster

---

backend/prisma/seed.ts

Motivation
----------
We wanted to check how our application behaves with 2000 users.
Backend-wise there is no problem (64ms).
The browser will slow down on this screen with too many users.
How to test
-----------
1. `docker compose down -v`
2. `docker compose up`
3. Create a table at http://localhost:3000/
close #2773

build(backend): seed 2000 users instead of 100

---

backend/src/server/sentry/createApolloPlugin.ts
backend/src/server/sentry/index.setupExpress.spec.ts
docker-compose.yml

Motivation
----------
Apollo server in more recent versions has a number of hooks that get called. E.g. `requestDidStart.didEncounterErrors` hook would not be called if the context creation already failed.
I also added `startupDidFail` for convenience.
I did not (yet) add `invalidRequestWasReceived` or `didEncounterSubsequentErrors`.
See the Apollo reference: https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference
How to test
-----------
1. `npm run test:unit -- --no-coverage src/server/sentry/index.setupExpress.spec.ts`
2. Tests pass
fix: #2644

fix(backend): capture context creation error

---

backend/prisma/migrations/20241023112212_add_invitation_links_related_to_user_and_redeemer/migration.sql
backend/prisma/schema.prisma
backend/src/graphql/models/InvitationModel.ts
backend/src/graphql/resolvers/UserResolver.spec.ts
backend/src/graphql/resolvers/UserResolver.ts
backend/test/helpers.ts

Motivation
----
We want to validate the invitation link before we send the user to the registration.
Solution
----
Query to validate the code, that gives back the name of the user that invited you
```
query($code: String!) {
validateInvitationLink(code: $code) {
name
}
}
```
Success
```
{
"data": {
"validateInvitationLink": {
"name": "authentik Default Admin"
}
}
}
```
Issues
----
- relates #2255

feat(backend): query to validate the invitation
